import { Geist, Geist_Mono } from "next/font/google";
 import "../globals.css";
import Header from "@/components/websitecomponent/Header";
import Footer from "@/components/websitecomponent/Footer";
import Storeprovider from "@/redux/Storeprovider";
import { getuser } from "@/api/user";
import { use } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const userData= await getuser()
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
        <Storeprovider>
        <Header userData = {userData}/>
    
        {children}
        
        <Footer/>
        </Storeprovider>
        
      </body>
    </html>
  );
}

