import { Geist, Geist_Mono } from "next/font/google";
   import "../globals.css";

import Footer from "@/components/admincomponent/Footer";
import Header from "@/components/admincomponent/Header";
import Sidebar from "@/components/admincomponent/Sidebar";
  import { ToastContainer, toast } from 'react-toastify';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-100vh flex">
             <ToastContainer
position="top-center"
autoClose={5000}
hideProgressBar={false}
newestOnTop={false}
closeOnClick={false}
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="dark"

/>
          
        <Sidebar/>
        <div className="flex-1">
          <Header/>
          <main className="p-6">
        {children}

          </main>
        </div>

        </div>
      </body>
    </html>
  );
}
